### ISSUE TITLE
failed to send notification to generic webhook: server returned unexpected response status code: 400 Bad Request

### ISSUE THREAD

**Issue by XBadFellaX** [nicholas-fedor/watchtower#1110]
### Describe the bug

Same issue as #826 

```
time="2025-12-17T18:15:28-06:00" level=info msg="Starting HTTP API server" addr=":8080"
time="2025-12-17T18:15:28-06:00" level=info msg="Watchtower 1.13.0 using Docker API v1.51"
time="2025-12-17T18:15:28-06:00" level=info msg="Using notifications: generic"
time="2025-12-17T18:15:28-06:00" level=info msg="HTTP API and periodic updates enabled"
time="2025-12-17T18:15:28-06:00" level=info msg="Next scheduled run: 2025-12-17 21:00:00 CST in 2 hours, 44 minutes, 31 seconds"
time="2025-12-17T18:15:28-06:00" level=info msg="The HTTP API is enabled at :8080."
time="2025-12-17T18:15:28-06:00" level=error msg="Failed to send shoutrrr notification" error="failed to send notification to generic webhook: server returned unexpected response status code: 400 Bad Request" failure_type=unknown index=0 notify=no service=generic url="generic://notifiarr.com"
time="2025-12-17T18:15:28-06:00" level=warning msg="Notification send completed with failures" auth_failures=0 failed_count=1 network_failures=0 notify=no rate_limit_failures=0 success_count=0 total_urls=1
```

### Steps to reproduce

```
services: 
 # WatchTower - Automatic Docker Container Updates
  watchtower:
    image: nickfedor/watchtower:latest #beatkind/watchtower:latest #
    container_name: watchtower
    restart: unless-stopped
    networks:
      - socket_proxy
    depends_on:
      - socket-proxy
    ports:
      - "8331:8080"
    environment:
      TZ: $TZ
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: "BadFella Server"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "false"
      # WATCHTOWER_RUN_ONCE: "true"
      WATCHTOWER_SCHEDULE: "00 00 21 * * *" # Everyday at 21:00
      # WATCHTOWER_POLL_INTERVAL: 36000
      WATCHTOWER_DISABLE_CONTAINERS: traefik,authelia,authentik,authentik-worker,crowdsec,socket-proxy,mariadb,postgresql,redis,plex,immich,immich-db
      WATCHTOWER_NOTIFICATION_REPORT: "true" # Enable when using beatkind image, Disable when using nickfedor image.
      WATCHTOWER_NOTIFICATION_URL: <redacted>
      WATCHTOWER_NOTIFICATIONS: "shoutrrr"
      WATCHTOWER_NOTIFICATIONS_LEVEL: info
      WATCHTOWER_HTTP_API_UPDATE: "true"
      WATCHTOWER_HTTP_API_METRICS: "true"
      WATCHTOWER_HTTP_API_TOKEN: watchhomepgapi
      WATCHTOWER_HTTP_API_PERIODIC_POLLS: "true"
      DOCKER_HOST: tcp://socket-proxy:2375
    secrets:
      - watchtower_notifications
```

### Expected behavior

Notifications work without error with generic service: https://shoutrrr.nickfedor.com/v0.13.1/services/specialized/generic/

### Screenshots

It does send a notification this time as opposed to last time but the logs show errors so not sure if its working or not.

<img width="470" height="228" alt="Image" src="https://github.com/user-attachments/assets/07085869-9fd5-4367-bdfd-44bdf1963b74" />

### Environment

```
badfella@ubuntu:~$ sudo uname -mr && docker version
6.17.4-1-pve x86_64
Client: Docker Engine - Community
 Version:           29.1.3
 API version:       1.52
 Go version:        go1.25.5
 Git commit:        f52814d
 Built:             Fri Dec 12 14:49:32 2025
 OS/Arch:           linux/amd64
 Context:           default
```

### Your logs

```text
time="2025-12-17T18:15:28-06:00" level=info msg="Starting HTTP API server" addr=":8080"
time="2025-12-17T18:15:28-06:00" level=info msg="Watchtower 1.13.0 using Docker API v1.51"
time="2025-12-17T18:15:28-06:00" level=info msg="Using notifications: generic"
time="2025-12-17T18:15:28-06:00" level=info msg="HTTP API and periodic updates enabled"
time="2025-12-17T18:15:28-06:00" level=info msg="Next scheduled run: 2025-12-17 21:00:00 CST in 2 hours, 44 minutes, 31 seconds"
time="2025-12-17T18:15:28-06:00" level=info msg="The HTTP API is enabled at :8080."
time="2025-12-17T18:15:28-06:00" level=error msg="Failed to send shoutrrr notification" error="failed to send notification to generic webhook: server returned unexpected response status code: 400 Bad Request" failure_type=unknown index=0 notify=no service=generic url="generic://notifiarr.com"
time="2025-12-17T18:15:28-06:00" level=warning msg="Notification send completed with failures" auth_failures=0 failed_count=1 network_failures=0 notify=no rate_limit_failures=0 success_count=0 total_urls=1
```

### Additional context

Do I need to configure something differently for this to work?

**Comment by nicholas-fedor** [comment]
There's a good chance the issue stems from the use of Shoutrrr's generic service, which sends plain text by default, rather than using the JSON payloads that Notifiarr expects.

My fork of Watchtower also includes my fork of Shoutrrr, which directly supports [Notifiarr](https://shoutrrr.nickfedor.com/latest/services/specialized/notifiarr/#notifiarr).

Try using something like the following:

```yaml
services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    networks:
      - socket_proxy
    depends_on:
      - socket-proxy
    ports:
      - "8331:8080"
    environment:
      TZ: $TZ
      WATCHTOWER_NOTIFICATIONS: "shoutrrr"
      WATCHTOWER_NOTIFICATION_URL: notifiarr://yourapikey@notifiarr.com
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: "BadFella Server"
      WATCHTOWER_NOTIFICATION_REPORT: "true" # Enable when using beatkind image, Disable when using nickfedor image.
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      # WATCHTOWER_RUN_ONCE: "true"
      WATCHTOWER_SCHEDULE: "00 00 21 * * *" # Everyday at 21:00
      # WATCHTOWER_POLL_INTERVAL: 36000
      WATCHTOWER_DISABLE_CONTAINERS: traefik,authelia,authentik,authentik-worker,crowdsec,socket-proxy,mariadb,postgresql,redis,plex,immich,immich-db
      WATCHTOWER_HTTP_API_UPDATE: "true"
      WATCHTOWER_HTTP_API_METRICS: "true"
      WATCHTOWER_HTTP_API_TOKEN: watchhomepgapi
      WATCHTOWER_HTTP_API_PERIODIC_POLLS: "true"
      DOCKER_HOST: tcp://socket-proxy:2375
    secrets:
      - watchtower_notifications
```

This just omits a few of the configuration items that were using default settings and uses the Notifiarr service for Shoutrrr instead of the Generic service. You will want to update the URL per your needs.

Please let me know if that resolves the issue.

---

Edit:

I have confirmed that the suggested URL is inaccurate and the generic URL provided by Notifiarr is functional.

**Comment by XBadFellaX** [comment]
> notifiarr://yourapikey@notifiarr.com

Tried what you suggested, getting a different error now. The API is the same I used in the generic string.

<img width="1614" height="495" alt="Image" src="https://github.com/user-attachments/assets/e15799e4-e1b5-4637-8dce-9387c16d7c72" />


```
badfella@ubuntu:~$ sudo docker logs watchtower
time="2025-12-17T20:53:40-06:00" level=info msg="Starting HTTP API server" addr=":8080"
time="2025-12-17T20:53:40-06:00" level=info msg="Watchtower 1.13.0 using Docker API v1.51"
time="2025-12-17T20:53:40-06:00" level=info msg="Using notifications: notifiarr"
time="2025-12-17T20:53:40-06:00" level=info msg="HTTP API and periodic updates enabled"
time="2025-12-17T20:53:40-06:00" level=info msg="Next scheduled run: 2025-12-17 21:00:00 CST in 6 minutes, 19 seconds"
time="2025-12-17T20:53:40-06:00" level=info msg="The HTTP API is enabled at :8080."
time="2025-12-17T20:53:40-06:00" level=warning msg="Authentication failure detected - check API keys/tokens" error="failed to send notification to Notifiarr: server returned unexpected response status code: 401 Unauthorized" failure_type=authentication index=0 notify=no service=notifiarr url="notifiarr://notifiarr.com"
time="2025-12-17T20:53:40-06:00" level=warning msg="Notification send completed with failures" auth_failures=1 failed_count=1 network_failures=0 notify=no rate_limit_failures=0 success_count=0 total_urls=1
time="2025-12-17T20:53:40-06:00" level=warning msg="Authentication failure detected - check API keys/tokens" error="failed to send notification to Notifiarr: server returned unexpected response status code: 401 Unauthorized" failure_type=authentication index=0 notify=no service=notifiarr url="notifiarr://notifiarr.com"
time="2025-12-17T20:53:40-06:00" level=warning msg="Notification send completed with failures" auth_failures=1 failed_count=1 network_failures=0 notify=no rate_limit_failures=0 success_count=0 total_urls=1
badfella@ubuntu:~$
```

**Comment by XBadFellaX** [comment]
Here is a screenshot from my Notifiarr account regarding Watchtower on how it should be configured, if it helps in any way on configuring your shoutarr instance to work with this.

<img width="1581" height="501" alt="Image" src="https://github.com/user-attachments/assets/14de460d-ae55-4739-b62d-589033dfab0a" />

**Comment by XBadFellaX** [comment]
![Image](https://github.com/user-attachments/assets/8f864904-7493-4207-8faa-5093eedd110b)

My watchtower schedule just ran with my initially posted compose file. Even though it still has the error about failed to send notification to generic webhook: server returned unexpected response status code: 400 Bad Request, I got a notification on discord just fine.

So it seems to be working due to some changes you made in #826, but the error is something that shouldn't be showing up in this case then.

Let me know your thoughts.

**Comment by nicholas-fedor** [comment]
I'm currently doing some e2e testing on this.
From what I'm seeing, Shoutrrr's Notifiarr service definitely requires some work.
That said, I was able to get the "generic" service working fine using the integration-specific URL that's provided.

Test setup:

```yaml
services:
  watchtower:
    image: nickfedor/watchtower:test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_RUN_ONCE=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_NOTIFICATION_REPORT=true
      - WATCHTOWER_NOTIFICATION_URL=generic://notifiarr.com/api/v1/notification/watchtower/<integration-api-token>?template=json
    networks:
      - watchtower-test
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - watchtower-test
networks:
  watchtower-test:
    name: watchtower-test
    external: false
```

The inclusion of the nginx image is just to ensure updates are being handled correctly.
I used the following basic script to retag the image:

```bash
#!/bin/bash

IMAGE_NAME="nginx"
OLD_TAG="1.29.3"
NEW_TAG="latest"

pull() {
    docker pull "$IMAGE_NAME:$OLD_TAG"
}

tag() {
    docker tag "$IMAGE_NAME:$OLD_TAG" "$IMAGE_NAME:$NEW_TAG"
}

pull && tag
```

Running the above Watchtower config, I was not seeing any warnings. 
I also tested the addition of the API configuration and that didn't have any impact.

**Comment by nicholas-fedor** [comment]
There are bugs in Shoutrrr that have been identified and fixes are expected to help address the issues that you have identified.

**Comment by nicholas-fedor** [comment]
I did some extensive integration testing with the changes in https://github.com/nicholas-fedor/shoutrrr/pull/535 that should hopefully resolve everything.

When it comes to Watchtower, the generic service, that Notifiarr recommends, should be used, as they have their own parsing/integration based off it. 

If someone were to use Shoutrrr's Notifiarr service for their notification URL, then they would just need to ensure they include the name and Discord Channel ID parameters for things to work.

**Comment by nicholas-fedor** [comment]
Keeping this open for the time being.

**Comment by austinwbest** [comment]
This is fixed on nigtly, the problem is the change to the payload. Previously it was looking for "Watchtower" to begin with and now it sends "API server" so parsing was failing. I changed the code to accept both so the next push to prod will take care of it.

**Comment by nicholas-fedor** [comment]
I went ahead and tested again after integrating the update to Shoutrrr.
Looks like the Watchtower <-> Notifiarr notifications are working fine now with their recommended generic URL.

Shoutrrr's Notifiarr service URL seems to be semi-functional, but requires using their Passthrough integration and using the legacy/non-report Watchtower notifications. If someone wants to use Notifiarr to pass through legacy notifications, then that's possible, but at that point it's probably better to just setup the Discord webhook and send the message directly instead.


Closing this issue as completed.

**Comment by XBadFellaX** [comment]
Just want to provide a quick update on 1.13.1 @nicholas-fedor as it does not fix the 400 errors in the logs:

Something to worry about after Christmas break, enjoy the holidays. Merry Christmas, thanks for all you do!

```
time=2025-12-23T17:59:04-06:00
level=info
msg=Starting HTTP API server
addr=:8080
time=2025-12-23T17:59:04-06:00
level=info
msg=Watchtower 1.13.1 using Docker API v1.51
time=2025-12-23T17:59:04-06:00
level=info
msg=Using notifications: generic
time=2025-12-23T17:59:04-06:00
level=info
msg=HTTP API and periodic updates enabled
time=2025-12-23T17:59:04-06:00
level=info
msg=Next scheduled run: 2025-12-23 21:00:00 CST in 3 hours, 55 seconds
time=2025-12-23T17:59:04-06:00
level=info
msg=The HTTP API is enabled at :8080.
time=2025-12-23T17:59:05-06:00
level=error
msg=Failed to send shoutrrr notification
error=failed to send notification to generic webhook: server returned unexpected response status code: 400 Bad Request
failure_type=unknown
index=0
notify=no
service=generic
url=generic://notifiarr.com
time=2025-12-23T17:59:05-06:00
level=warning
msg=Notification send completed with failures
auth_failures=0
failed_count=1
network_failures=0
notify=no
rate_limit_failures=0
success_count=0
total_urls=1
```

**Comment by nicholas-fedor** [comment]
Those logs look like they are from the initial startup.

I just did a fresh test run with the following config:

```yaml
services:
  watchtower:
    image: nickfedor/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_RUN_ONCE=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_NOTIFICATION_REPORT=true
      - WATCHTOWER_NOTIFICATION_URL=/run/secrets/watchtower_notification_url
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_API_UPDATE=true
      - WATCHTOWER_API_METRICS=true
      - WATCHTOWER_API_PERIODIC_POLLS=true
      - WATCHTOWER_API_TOKEN=supersecrettoken
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=Watchtower Testing
    networks:
      - watchtower-test
    restart: unless-stopped
    secrets:
      - watchtower_notification_url
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - watchtower-test
networks:
  watchtower-test:
    name: watchtower-test
    external: false
secrets:
  watchtower_notification_url:
    file: ./WATCHTOWER_NOTIFICATION_URL
```

This is using the exact 'integration-specific' URL that Notifiarr provides.

```text
time="2025-12-24T00:59:03Z" level=debug msg="SendNotification called - sending queued entries and report" entries_count=3 legacy_template=false notify=no report_available=false
time="2025-12-24T00:59:03Z" level=debug msg="Starting template processing for notification message" container_count=0 entries_count=3 legacy_template=false notify=no report_available=false
time="2025-12-24T00:59:03Z" level=debug msg="Template processing completed successfully" entries_count=3 legacy_template=false msg_length=96 notify=no template_name=
time="2025-12-24T00:59:03Z" level=debug msg="Generated notification message" message="Watchtower 1.13.1 using Docker API v1.51\nUsing notifications: generic\nRunning a one time update\n" notify=no
time="2025-12-24T00:59:03Z" level=debug msg="Preparing to send entries" error="<nil>" message="Watchtower 1.13.1 using Docker API v1.51\nUsing notifications: generic\nRunning a one time update\n" notify=no
time="2025-12-24T00:59:03Z" level=debug msg="Checking notifier state before queuing message" closed=false entries_count=3 msg_length=96 notify=no receiving=true
time="2025-12-24T00:59:03Z" level=debug msg="Queuing notification message to channel" entries_count=3 msg_length=96 notification_type=shoutrrr notify=no
time="2025-12-24T00:59:03Z" level=debug msg="Successfully sent message to notification channel" channel_status=sent entries_count=3 msg_length=96 notify=no
```

There were issues before with your original configuration.
Share what you're using now, as I'm not seeing issues based on my e2e testing, as shown above.

**Comment by austinwbest** [comment]
@XBadFellaX if you want to try on nightly just shoot me a message on the discord server and that should clear things up
