### ISSUE TITLE
Multiple connection errors during pull: failed to get token; failed to execute challenge request; failed to execute HTTP request

### ISSUE THREAD

**Issue by xXSalamanderXx** [nicholas-fedor/watchtower#997]
### Describe the bug

Getting multiple connection errors during pull, this happens for every container. My connection is perfect and I can connect manually via ping `index.docker.io and ping ghcr.io`.

Error started 2 days ago but has been working flawlessly until then. I haven't changed anything in my setup.

`{"time":"2025-11-30T20:31:16+00:00","level":"warning","msg":"Digest retrieval failed, falling back to full pull","container":"watchtower","error":"failed to get token: failed to execute challenge request: failed to execute HTTP request: Get \\\"https://index.docker.io/v2/\\\": dial tcp: lookup index.docker.io on 127.0.0.11:53: server misbehaving","image":"nickfedor/watchtower:latest"}`

### Steps to reproduce

1. Run watchtower via docker compose on a schedule (every 30 mins)
2. Errors begin

### Expected behavior

Successful updates, no connection issues.

### Environment

- Platform (Debian 13)
- Architecture (x64)
- Docker Version (Latest)

### Your logs

```text
`{"time":"2025-11-30T20:31:16+00:00","level":"warning","msg":"Digest retrieval failed, falling back to full pull","container":"watchtower","error":"failed to get token: failed to execute challenge request: failed to execute HTTP request: Get \\\"https://index.docker.io/v2/\\\": dial tcp: lookup index.docker.io on 127.0.0.11:53: server misbehaving","image":"nickfedor/watchtower:latest"}`
```

**Comment by nicholas-fedor** [comment]
This is a Docker DNS issue related to https://github.com/docker/cli/issues/6684 and the upstream https://github.com/moby/moby/issues/51614 that was fixed by https://github.com/moby/moby/pull/51615

Update your version of Docker to 29.1.1-1 to resolve the issue.

**Comment by xXSalamanderXx** [comment]
> This is a Docker DNS issue related to [docker/cli#6684](https://github.com/docker/cli/issues/6684) and the upstream [moby/moby#51614](https://github.com/moby/moby/issues/51614) that was fixed by [moby/moby#51615](https://github.com/moby/moby/pull/51615)
> 
> Update your version of Docker to 29.1.1-1 to resolve the issue.

I am already on the latest version of Docker. So this won't fix the issue. Maybe it's still not resolved yet.
```
~$ docker --version
Docker version 29.1.1, build 0aedba5
```
